<?require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
$APPLICATION->SetTitle('Блог');
?>
<?$APPLICATION->IncludeComponent(
	'bitrix:news',
	'blog',
	Array(
		'ADD_ELEMENT_CHAIN' => 'Y',
		'ADD_SECTIONS_CHAIN' => 'Y',
		'AJAX_MODE' => 'N',
		'AJAX_OPTION_ADDITIONAL' => '',
		'AJAX_OPTION_HISTORY' => 'N',
		'AJAX_OPTION_JUMP' => 'N',
		'AJAX_OPTION_STYLE' => 'N',
		'BROWSER_TITLE' => '-',
		'CACHE_FILTER' => 'N',
		'CACHE_GROUPS' => 'Y',
		'CACHE_TIME' => '36000000',
		'CACHE_TYPE' => 'N',
		'CHECK_DATES' => 'Y',
		'DETAIL_ACTIVE_DATE_FORMAT' => 'd.m.Y',
		'DETAIL_DISPLAY_BOTTOM_PAGER' => 'Y',
		'DETAIL_DISPLAY_TOP_PAGER' => 'N',
		'DETAIL_FIELD_CODE' => array(0=>'CODE',1=>'NAME',2=>'SORT',3=>'PREVIEW_PICTURE',4=>'DETAIL_TEXT',5=>'',),
		'DETAIL_PAGER_SHOW_ALL' => 'N',
		'DETAIL_PAGER_TEMPLATE' => '',
		'DETAIL_PAGER_TITLE' => 'Страница',
		'DETAIL_PROPERTY_CODE' => array(0=>'MORE_PHOTO',1=>'',),
		'DETAIL_SET_CANONICAL_URL' => 'Y',
		'DISPLAY_BOTTOM_PAGER' => 'N',
		'DISPLAY_DATE' => 'Y',
		'DISPLAY_NAME' => 'Y',
		'DISPLAY_PICTURE' => 'Y',
		'DISPLAY_PREVIEW_TEXT' => 'Y',
		'DISPLAY_TOP_PAGER' => 'N',
		'HIDE_LINK_WHEN_NO_DETAIL' => 'N',
		'IBLOCK_ID' => \Dao\App::ib('Blog')->id(),
		'IBLOCK_TYPE' => 'blog',
		'INCLUDE_IBLOCK_INTO_CHAIN' => 'Y',
		'LIST_ACTIVE_DATE_FORMAT' => 'd.m.Y',
		'LIST_FIELD_CODE' => array(0=>'CODE',1=>'NAME',2=>'SORT',3=>'PREVIEW_TEXT',4=>'PREVIEW_PICTURE',5=>'DATE_ACTIVE_FROM',6=>'',),
		'LIST_PROPERTY_CODE' => array(0=>'',1=>'',),
		'MESSAGE_404' => '',
		'META_DESCRIPTION' => '-',
		'META_KEYWORDS' => '-',
		'NEWS_COUNT' => '24',
		'PAGER_BASE_LINK_ENABLE' => 'N',
		'PAGER_DESC_NUMBERING' => 'N',
		'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
		'PAGER_SHOW_ALL' => 'N',
		'PAGER_SHOW_ALWAYS' => 'N',
		'PAGER_TEMPLATE' => '.default',
		'PAGER_TITLE' => 'Новости',
		'PREVIEW_TRUNCATE_LEN' => '',
		'SEF_FOLDER' => '/blog/',
		'SEF_MODE' => 'Y',
		'SEF_URL_TEMPLATES' => array('detail'=>'#ELEMENT_CODE#/','news'=>'','section'=>'#SECTION_CODE_PATH#/',),
		'SET_LAST_MODIFIED' => 'Y',
		'SET_STATUS_404' => 'Y',
		'SET_TITLE' => 'Y',
		'SHOW_404' => 'N',
		'SORT_BY1' => 'ACTIVE_FROM',
		'SORT_BY2' => 'SORT',
		'SORT_ORDER1' => 'DESC',
		'SORT_ORDER2' => 'ASC',
		'STRICT_SECTION_CHECK' => 'N',
		'USE_CATEGORIES' => 'N',
		'USE_FILTER' => 'N',
		'USE_PERMISSIONS' => 'N',
		'USE_RATING' => 'N',
		'USE_RSS' => 'N',
		'USE_SEARCH' => 'N',
		'USE_SHARE' => 'N'
	)
);?>
<?require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');?>